DRY test setup (#79)
* DRY test setup

I had these unstaged changes from my work on
https://github.com/coopdevs/decidim-module-action_delegator/pull/77.
They are still worth it.

* Remove deprecated set-env GH Workflow command

This fixes the CI error:

```
Run echo ::set-env name=workspace::$GITHUB_WORKSPACE
Error: Unable to process command '::set-env name=workspace::/home/runner/work/decidim-module-action_delegator/decidim-module-action_delegator' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

* Temporarily skip erblint in CI

We should be able to enable it back once Decidim upgrades erblint.
That's already done in develop so it won't be earlier than 0.24.